version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"

  kafka:
    image: spotify/kafka
    ports:
      - "2181"
      - "9092"
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
